# -*- coding: utf-8 -*-
"""fraud detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFgON1dnz1rpbvLpF-s3XJK0XSZcXMbg
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.preprocessing import StandardScaler, LabelEncoder

from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    precision_score, recall_score, roc_auc_score,
    confusion_matrix, roc_curve, classification_report
)

from imblearn.pipeline import Pipeline as Imbpipeline

from imblearn.over_sampling import SMOTE

pip install imbalanced-learn

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

DATA_PATH = "Dataset for Data Analytics.csv"

df = pd.read_csv(DATA_PATH)

print("Original dataset shape:", df.shape)

print(df.head())

risk_score = (
    (df["OrderStatus"] == "Cancelled").astype(int) * 2 +
    (df["PaymentMethod"].isin(["cash", "Gift Card"])).astype(int) * 2 +
    (df["TotalPrice"]>df["TotalPrice"].quantile(0.85)).astype(int) * 2 +
    (df["CouponCode"].isin([])).astype(int) * 1 +
    (df["ItemsInCart"] > df["ItemsInCart"].quantile(0.90)).astype(int) * 1
)

prob_fraud = (risk_score / risk_score.max()) ** 3

prob_fraud = prob_fraud * 0.5 + np.random.rand(len(df)) * 0.03

threshold = np.quantile(prob_fraud, 0.95)
df["IsFraud"] = (prob_fraud > threshold).astype(int)

print("\nSynthetic fraud label created.")
print(df["IsFraud"].value_counts())
print("Fraud rate: {:.2f}%".format(df["IsFraud"].mean() * 100))

counts = df["IsFraud"].value_counts().sort_index()
labels = ["Legitimate (0)", "Fraudulent (1)"]

plt.figure(figsize=(6, 5))
bars = plt.bar(labels, counts.values, color=["#3B82A0", "#E2725B"])
for bar, val in zip(bars, counts.values):
    plt.text(bar.get_x() + bar.get_width() / 2, val + 2, str(val),
              ha="center", fontweight="bold")
plt.title("Class Imbalance: Legitimate vs Fraudulent Orders")
plt.ylabel("Number of Orders")
plt.tight_layout()
plt.savefig("plot_1_class_imbalance.png", dpi=150)
plt.show()

drop_cols = ["OrderID", "CustomerID", "ShippingAddress", "TrackingNumber", "Date"]
features_df = df.drop(columns=drop_cols + ["IsFraud"])
target = df["IsFraud"]

features_df["CouponCode"] = features_df["CouponCode"].fillna("NoCoupon")

categorical_cols = [c for c in features_df.columns
                     if features_df[c].dtype == object or str(features_df[c].dtype) in ("str", "string")]

encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    features_df[col] = le.fit_transform(features_df[col].astype(str))
    encoders[col] = le

print("\nFinal feature columns used for modeling:")
print(list(features_df.columns))

X = features_df
y = target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
)

print("\nTrain shape:", X_train.shape, " Test shape:", X_test.shape)
print("Train fraud rate: {:.2f}%".format(y_train.mean() * 100))
print("Test fraud rate : {:.2f}%".format(y_test.mean() * 100))

from imblearn.pipeline import Pipeline as ImbPipeline

log_reg_pipeline = ImbPipeline(steps=[
    ("scaler", StandardScaler()),
    ("smote", SMOTE(random_state=RANDOM_STATE)),
    ("classifier", LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))
])

# Random Forest does NOT need scaling (tree splits are scale-invariant)
rf_pipeline = ImbPipeline(steps=[
    ("smote", SMOTE(random_state=RANDOM_STATE)),
    ("classifier", RandomForestClassifier(random_state=RANDOM_STATE))
])

log_reg_param_grid = {
    "smote__k_neighbors": [3, 5],
    "classifier__C": [0.01, 0.1, 1.0]
}

rf_param_grid = {
    "smote__k_neighbors": [3, 5],
    "classifier__n_estimators": [100, 200],
    "classifier__max_depth": [10, 20, None]
}

# We optimize for ROC-AUC (best single metric for imbalanced fraud detection)
log_reg_grid = GridSearchCV(
    log_reg_pipeline, log_reg_param_grid,
    scoring="roc_auc", cv=5, n_jobs=-1
)

rf_grid = GridSearchCV(
    rf_pipeline, rf_param_grid,
    scoring="roc_auc", cv=5, n_jobs=-1
)

print("\nTraining Logistic Regression (with GridSearchCV)...")
log_reg_grid.fit(X_train, y_train)
print("Best Logistic Regression params:", log_reg_grid.best_params_)

print("\nTraining Random Forest (with GridSearchCV)...")
rf_grid.fit(X_train, y_train)
print("Best Random Forest params:", rf_grid.best_params_)

best_log_reg = log_reg_grid.best_estimator_
best_rf = rf_grid.best_estimator_

def evaluate_model(model, name, X_test, y_test):
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    precision = precision_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred, zero_division=0)
    roc_auc = roc_auc_score(y_test, y_proba)

    print(f"\n===== {name} : Test Set Results =====")
    print(f"Precision : {precision:.3f}  (when we flag fraud, how often are we right?)")
    print(f"Recall    : {recall:.3f}  (out of all real fraud, how much did we catch?)")
    print(f"ROC-AUC   : {roc_auc:.3f}  (overall ability to separate the two classes)")
    print(classification_report(y_test, y_pred, target_names=["Legitimate", "Fraud"]))

    return {
        "name": name, "y_pred": y_pred, "y_proba": y_proba,
        "precision": precision, "recall": recall, "roc_auc": roc_auc
    }


results_log_reg = evaluate_model(best_log_reg, "Logistic Regression", X_test, y_test)
results_rf = evaluate_model(best_rf, "Random Forest", X_test, y_test)

fig, axes = plt.subplots(1, 2, figsize=(11, 5))

for ax, res in zip(axes, [results_log_reg, results_rf]):
    cm = confusion_matrix(y_test, res["y_pred"])
    im = ax.imshow(cm, cmap="Blues")
    ax.set_title(f"{res['name']}\nConfusion Matrix")
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    ax.set_xticks([0, 1]); ax.set_xticklabels(["Legit", "Fraud"])
    ax.set_yticks([0, 1]); ax.set_yticklabels(["Legit", "Fraud"])
    for i in range(2):
        for j in range(2):
            ax.text(j, i, cm[i, j], ha="center", va="center",
                     color="white" if cm[i, j] > cm.max() / 2 else "black",
                     fontsize=14, fontweight="bold")

plt.tight_layout()
plt.savefig("plot_2_confusion_matrices.png", dpi=150)
plt.show()

plt.figure(figsize=(7, 6))

for res, color in zip([results_log_reg, results_rf], ["#3B82A0", "#E2725B"]):
    fpr, tpr, _ = roc_curve(y_test, res["y_proba"])
    plt.plot(fpr, tpr, color=color, linewidth=2,
              label=f"{res['name']} (AUC = {res['roc_auc']:.3f})")

plt.plot([0, 1], [0, 1], linestyle="--", color="gray", label="Random Guess")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend(loc="lower right")
plt.tight_layout()
plt.savefig("plot_3_roc_curves.png", dpi=150)
plt.show()

metrics_names = ["Precision", "Recall", "ROC-AUC"]
log_vals = [results_log_reg["precision"], results_log_reg["recall"], results_log_reg["roc_auc"]]
rf_vals = [results_rf["precision"], results_rf["recall"], results_rf["roc_auc"]]

x = np.arange(len(metrics_names))
width = 0.35

plt.figure(figsize=(7, 5))
plt.bar(x - width / 2, log_vals, width, label="Logistic Regression", color="#3B82A0")
plt.bar(x + width / 2, rf_vals, width, label="Random Forest", color="#E2725B")
plt.xticks(x, metrics_names)
plt.ylim(0, 1)
plt.ylabel("Score")
plt.title("Model Comparison: Precision vs Recall vs ROC-AUC")
plt.legend()
plt.tight_layout()
plt.savefig("plot_4_metric_comparison.png", dpi=150)
plt.show()

rf_classifier = best_rf.named_steps["classifier"]
importances = rf_classifier.feature_importances_
feat_names = X.columns

sorted_idx = np.argsort(importances)[::-1]

plt.figure(figsize=(8, 5))
plt.bar(range(len(importances)), importances[sorted_idx], color="#4C9A6A")
plt.xticks(range(len(importances)), feat_names[sorted_idx], rotation=45, ha="right")
plt.ylabel("Importance")
plt.title("Random Forest: Feature Importance")
plt.tight_layout()
plt.savefig("plot_5_feature_importance.png", dpi=150)
plt.show()

print("\n================ FINAL SUMMARY ================")
print(f"Logistic Regression -> Precision: {results_log_reg['precision']:.3f} | "
      f"Recall: {results_log_reg['recall']:.3f} | ROC-AUC: {results_log_reg['roc_auc']:.3f}")
print(f"Random Forest        -> Precision: {results_rf['precision']:.3f} | "
      f"Recall: {results_rf['recall']:.3f} | ROC-AUC: {results_rf['roc_auc']:.3f}")

better_model = "Random Forest" if results_rf["roc_auc"] >= results_log_reg["roc_auc"] else "Logistic Regression"
print(f"\nBest performing model by ROC-AUC: {better_model}")
print("All plots saved as PNG files in the current folder.")
print("=================================================")

